### ISSUE TITLE
Install issue onnxruntime-gpu

### ISSUE THREAD

**Issue by scooper86** [LykosAI/ComfyUI-Inference-Core-Nodes#4]
im running python3.11 on windows, pretty sure its a version issue, is there any fix for this?

`ERROR: onnxruntime_gpu-1.17.1-cp310-cp310-win_amd64.whl is not a supported wheel on this platform`

**Comment by Aruen24** [comment]
I got the same problem

**Comment by ionite34** [comment]
Currently there's only a case for installing the wheel for Python 3.10 since that's what Stability Matrix was using. Will look to add support for 3.11 soon as well.

In the meantime, you can install manually by running via venv or embedded python in the ComfyUI-Inference-Core-Nodes folder:
```
-m pip install -e .
```
Then if you have the onnxruntime_gpu wheel for your python version you can individually install that for gpu support.
